#!/usr/bin/env python3
"""
Convert a JPEG image to a C byte-array header for embedding in firmware.

Usage:
    python3 tools/embed_image.py test.jpg > include/data/balloon_image.h
"""
import sys


def main():
    if len(sys.argv) < 2:
        print(f"Usage: {sys.argv[0]} <image.jpg> [array_name]", file=sys.stderr)
        sys.exit(1)

    path = sys.argv[1]
    name = sys.argv[2] if len(sys.argv) > 2 else "balloon_image"

    with open(path, "rb") as f:
        data = f.read()

    print("/* Auto-generated by embed_image.py — do not edit */")
    print("#ifndef BALLOON_IMAGE_H")
    print("#define BALLOON_IMAGE_H")
    print()
    print("#include <stdint.h>")
    print()
    print(f"#define {name.upper()}_SIZE {len(data)}u")
    print()
    print(f"static const uint8_t {name}[{len(data)}] = {{")

    for i in range(0, len(data), 16):
        chunk = data[i:i + 16]
        hex_vals = ", ".join(f"0x{b:02x}" for b in chunk)
        comma = "," if i + 16 < len(data) else ""
        print(f"    {hex_vals}{comma}")

    print("};")
    print()
    print("#endif /* BALLOON_IMAGE_H */")


if __name__ == "__main__":
    main()
